/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import classes.Ponto;
import classes.Quadrado;
import javax.swing.JOptionPane;

/**
 *
 * @author cristiane
 */
public class FrQuadrado extends javax.swing.JFrame {

    /**
     * Creates new form FrQuadrado
     */
    public FrQuadrado() {
        initComponents();
        this.habilitaCampos(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblTitulo = new javax.swing.JLabel();
        btnArea = new javax.swing.JButton();
        btnDistancia = new javax.swing.JButton();
        btnPerimetro = new javax.swing.JButton();
        lblEntrada = new javax.swing.JLabel();
        lblPontoA = new javax.swing.JLabel();
        edtAX = new javax.swing.JTextField();
        edtAY = new javax.swing.JTextField();
        lblPontoA1 = new javax.swing.JLabel();
        edtBX = new javax.swing.JTextField();
        edtBY = new javax.swing.JTextField();
        lblPontoA2 = new javax.swing.JLabel();
        edtCX = new javax.swing.JTextField();
        edtCY = new javax.swing.JTextField();
        lblPontoD = new javax.swing.JLabel();
        edtDX = new javax.swing.JTextField();
        edtDY = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        edtInfo = new javax.swing.JTextArea();
        btnDiagonal = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        lblTitulo.setFont(new java.awt.Font("Roboto Condensed", 0, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("CÁLCULO DE QUADRADO");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 69;
        gridBagConstraints.ipadx = 114;
        gridBagConstraints.ipady = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 5, 0, 0);
        getContentPane().add(lblTitulo, gridBagConstraints);

        btnArea.setBackground(java.awt.SystemColor.controlHighlight);
        btnArea.setFont(new java.awt.Font("Roboto Condensed", 0, 16)); // NOI18N
        btnArea.setText("Área");
        btnArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAreaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 47, 0, 0);
        getContentPane().add(btnArea, gridBagConstraints);

        btnDistancia.setBackground(java.awt.SystemColor.controlHighlight);
        btnDistancia.setFont(new java.awt.Font("Roboto Condensed", 0, 16)); // NOI18N
        btnDistancia.setText("Existência");
        btnDistancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDistanciaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 7, 0, 0);
        getContentPane().add(btnDistancia, gridBagConstraints);

        btnPerimetro.setBackground(java.awt.SystemColor.controlHighlight);
        btnPerimetro.setFont(new java.awt.Font("Roboto Condensed", 0, 16)); // NOI18N
        btnPerimetro.setText("Perímetro");
        btnPerimetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerimetroActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 40;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 15, 0, 0);
        getContentPane().add(btnPerimetro, gridBagConstraints);

        lblEntrada.setFont(new java.awt.Font("Roboto Condensed", 0, 16)); // NOI18N
        lblEntrada.setText("Insira as coordenadas:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(28, 24, 0, 0);
        getContentPane().add(lblEntrada, gridBagConstraints);

        lblPontoA.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        lblPontoA.setText("Ponto A");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 24, 0, 0);
        getContentPane().add(lblPontoA, gridBagConstraints);

        edtAX.setFont(new java.awt.Font("Roboto Condensed", 0, 16)); // NOI18N
        edtAX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtAXActionPerformed(evt);
            }
        });
        edtAX.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                edtAXKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 41;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 24, 0, 0);
        getContentPane().add(edtAX, gridBagConstraints);

        edtAY.setFont(new java.awt.Font("Roboto Condensed", 0, 16)); // NOI18N
        edtAY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtAYActionPerformed(evt);
            }
        });
        edtAY.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                edtAYKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 41;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 6, 0, 0);
        getContentPane().add(edtAY, gridBagConstraints);

        lblPontoA1.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        lblPontoA1.setText("Ponto B");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 12, 0, 0);
        getContentPane().add(lblPontoA1, gridBagConstraints);

        edtBX.setFont(new java.awt.Font("Roboto Condensed", 0, 16)); // NOI18N
        edtBX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtBXActionPerformed(evt);
            }
        });
        edtBX.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                edtBXKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.ipadx = 41;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 0, 0);
        getContentPane().add(edtBX, gridBagConstraints);

        edtBY.setFont(new java.awt.Font("Roboto Condensed", 0, 16)); // NOI18N
        edtBY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtBYActionPerformed(evt);
            }
        });
        edtBY.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                edtBYKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 18;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 22;
        gridBagConstraints.ipadx = 41;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 6, 0, 0);
        getContentPane().add(edtBY, gridBagConstraints);

        lblPontoA2.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        lblPontoA2.setText("Ponto C");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 40;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 0, 0);
        getContentPane().add(lblPontoA2, gridBagConstraints);

        edtCX.setFont(new java.awt.Font("Roboto Condensed", 0, 16)); // NOI18N
        edtCX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtCXActionPerformed(evt);
            }
        });
        edtCX.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                edtCXKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 40;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 41;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 18, 0, 0);
        getContentPane().add(edtCX, gridBagConstraints);

        edtCY.setFont(new java.awt.Font("Roboto Condensed", 0, 16)); // NOI18N
        edtCY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtCYActionPerformed(evt);
            }
        });
        edtCY.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                edtCYKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 41;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 27;
        gridBagConstraints.ipadx = 41;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 6, 0, 0);
        getContentPane().add(edtCY, gridBagConstraints);

        lblPontoD.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        lblPontoD.setText("Ponto D");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 68;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 0, 0);
        getContentPane().add(lblPontoD, gridBagConstraints);

        edtDX.setFont(new java.awt.Font("Roboto Condensed", 0, 16)); // NOI18N
        edtDX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtDXActionPerformed(evt);
            }
        });
        edtDX.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                edtDXKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 68;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 41;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 18, 0, 0);
        getContentPane().add(edtDX, gridBagConstraints);

        edtDY.setFont(new java.awt.Font("Roboto Condensed", 0, 16)); // NOI18N
        edtDY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtDYActionPerformed(evt);
            }
        });
        edtDY.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                edtDYKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 69;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 71;
        gridBagConstraints.ipadx = 41;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 6, 0, 0);
        getContentPane().add(edtDY, gridBagConstraints);

        btnCalcular.setBackground(new java.awt.Color(255, 102, 102));
        btnCalcular.setForeground(new java.awt.Color(255, 255, 255));
        btnCalcular.setText("CALCULAR");
        btnCalcular.setToolTipText("Clique aqui para calcular!");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 18;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 25;
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 0, 0);
        getContentPane().add(btnCalcular, gridBagConstraints);

        edtInfo.setEditable(false);
        edtInfo.setColumns(20);
        edtInfo.setRows(5);
        jScrollPane1.setViewportView(edtInfo);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 141;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 441;
        gridBagConstraints.ipady = 94;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 12, 20, 12);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        btnDiagonal.setBackground(java.awt.SystemColor.controlHighlight);
        btnDiagonal.setFont(new java.awt.Font("Roboto Condensed", 0, 16)); // NOI18N
        btnDiagonal.setText("Diagonal");
        btnDiagonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiagonalActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 68;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 70;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 15, 0, 0);
        getContentPane().add(btnDiagonal, gridBagConstraints);

        btnVoltar.setFont(new java.awt.Font("Roboto Condensed", 0, 16)); // NOI18N
        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/left-arrow.png"))); // NOI18N
        btnVoltar.setToolTipText("Voltar para a tela inicial");
        btnVoltar.setContentAreaFilled(false);
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = -8;
        gridBagConstraints.ipady = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 0, 0);
        getContentPane().add(btnVoltar, gridBagConstraints);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAreaActionPerformed
        this.habilitaCampos(true);
        this.botaoAcionado = 1;
    }//GEN-LAST:event_btnAreaActionPerformed

    private void btnDistanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDistanciaActionPerformed
        this.habilitaCampos(true);
        this.botaoAcionado = 2;
    }//GEN-LAST:event_btnDistanciaActionPerformed

    private void btnPerimetroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerimetroActionPerformed
        this.habilitaCampos(true);
        this.botaoAcionado = 3;
    }//GEN-LAST:event_btnPerimetroActionPerformed

    private void edtAXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtAXActionPerformed
        
    }//GEN-LAST:event_edtAXActionPerformed

    private void edtAYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtAYActionPerformed

    }//GEN-LAST:event_edtAYActionPerformed

    private void edtBXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtBXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtBXActionPerformed

    private void edtBYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtBYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtBYActionPerformed

    private void edtCXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtCXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtCXActionPerformed

    private void edtCYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtCYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtCYActionPerformed

    private void edtDXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtDXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtDXActionPerformed

    private void edtDYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtDYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtDYActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        
        if (this.verificaCampoPreenchido()) {

            this.copiaGuiParaClasse();
            String resultado = "";

            if (this.botaoAcionado == 1) {
                if(this.q.formaQuadrado(a, b, c, d)){
                
                    resultado = "\nA área do quadrado é: \n";
                    resultado = resultado + q.calculoArea(a, b);
                    this.edtInfo.setText(resultado + " cm²");

                }
                else{
                
                    this.edtInfo.setText("\n\n\tERRO! Não é possível calcular a área, pois"
                    +"\n\tas coordenadas não formam um quadrado.");
                    
                }

                
            } else if (this.botaoAcionado == 2) {
                
                if(this.q.formaQuadrado(a, b, c, d)){
                    
                    this.edtInfo.setText(this.q.imprimirPontosQuadrado(a, b, c, d) + "\nFORMAM UM QUADRADO!");
                }
                else{
                    
                    this.edtInfo.setText(this.q.imprimirPontosQuadrado(a, b, c, d) + "\nNÃO FORMAM UM QUADRADO!");
                }
                
            } else if (this.botaoAcionado == 3) {
                if(this.q.formaQuadrado(a, b, c, d)){
                
                    resultado = "\nO perímetro total é: \n" + this.q.calculoPerimetro(a, b);
                    this.edtInfo.setText(resultado + " cm");
                }
                else{
                
                    this.edtInfo.setText("\n\n\tERRO! Não é possível calcular o perímetro, pois"
                    +"\n\tas coordenadas não formam um quadrado.");
                }
            
            }else if(this.botaoAcionado == 4){
                
                if(this.q.formaQuadrado(a, b, c, d)){
                    
                    resultado = "\nA diagonal do quadrado vale: \n" + this.q.calculoDiagonal(a, b);
                    this.q.verificaQuadrado(a, b, c, d);
                    this.edtInfo.setText(resultado);
                }
                else{
                
                     this.edtInfo.setText("\n\n\tERRO! Não é possível calcular a diagonal, pois"
                    +"\n\t as coordenadas não formam um quadrado.");
                     
                }
            }
            
        }
        else{
        
            JOptionPane.showMessageDialog(this, "ERRO! Campo Vazio.");
        }
        
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnDiagonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiagonalActionPerformed
        this.habilitaCampos(true);
        this.botaoAcionado = 4;
    }//GEN-LAST:event_btnDiagonalActionPerformed

    private void edtAXKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtAXKeyReleased
        if(evt.getKeyChar() == java.awt.event.KeyEvent.VK_ENTER){
            this.edtAY.requestFocus();      
        }
    }//GEN-LAST:event_edtAXKeyReleased

    private void edtAYKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtAYKeyReleased
        if(evt.getKeyChar() == java.awt.event.KeyEvent.VK_ENTER){
            this.edtBX.requestFocus();      
        }
    }//GEN-LAST:event_edtAYKeyReleased

    private void edtBXKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtBXKeyReleased
        if(evt.getKeyChar() == java.awt.event.KeyEvent.VK_ENTER){
            this.edtBY.requestFocus();      
        }
    }//GEN-LAST:event_edtBXKeyReleased

    private void edtBYKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtBYKeyReleased
        if(evt.getKeyChar() == java.awt.event.KeyEvent.VK_ENTER){
            this.edtCX.requestFocus();      
        }
    }//GEN-LAST:event_edtBYKeyReleased

    private void edtCXKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtCXKeyReleased
        if(evt.getKeyChar() == java.awt.event.KeyEvent.VK_ENTER){
            this.edtCY.requestFocus();      
        }
    }//GEN-LAST:event_edtCXKeyReleased

    private void edtCYKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtCYKeyReleased
        if(evt.getKeyChar() == java.awt.event.KeyEvent.VK_ENTER){
            this.edtDX.requestFocus();      
        }
    }//GEN-LAST:event_edtCYKeyReleased

    private void edtDXKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtDXKeyReleased
        if(evt.getKeyChar() == java.awt.event.KeyEvent.VK_ENTER){
            this.edtDY.requestFocus();      
        }
    }//GEN-LAST:event_edtDXKeyReleased

    private void edtDYKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtDYKeyReleased
        if(evt.getKeyChar() == java.awt.event.KeyEvent.VK_ENTER){
            this.btnCalcular.requestFocus();      
        }
    }//GEN-LAST:event_edtDYKeyReleased

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.voltar();
    }//GEN-LAST:event_btnVoltarActionPerformed

    public void habilitaCampos(boolean flag){
    
        this.edtAX.setEnabled(flag);
        this.edtAY.setEnabled(flag);
        this.edtBX.setEnabled(flag);
        this.edtBY.setEnabled(flag);
        this.edtCX.setEnabled(flag);
        this.edtCY.setEnabled(flag);
        this.edtDX.setEnabled(flag);
        this.edtDY.setEnabled(flag);
        
    }
    
    public void converte(){
    
        this.edtAX.setText(this.edtAX.getText().replace(',' , '.'));
        this.edtAY.setText(this.edtAY.getText().replace(',', '.'));
        this.edtBX.setText(this.edtBX.getText().replace(',', '.'));
        this.edtBY.setText(this.edtBY.getText().replace(',', '.'));
        this.edtCX.setText(this.edtCX.getText().replace(',', '.'));
        this.edtCY.setText(this.edtCY.getText().replace(',', '.'));
        this.edtDX.setText(this.edtDX.getText().replace(',', '.'));
        this.edtDY.setText(this.edtDY.getText().replace(',', '.'));
    }
    
    public void copiaGuiParaClasse(){
    
        this.converte();
        
        this.a.setX(Double.parseDouble(this.edtAX.getText()));
        this.a.setY(Double.parseDouble(this.edtAY.getText()));
        this.b.setX(Double.parseDouble(this.edtBX.getText()));
        this.b.setY(Double.parseDouble(this.edtBY.getText()));
        this.c.setX(Double.parseDouble(this.edtCX.getText()));
        this.c.setY(Double.parseDouble(this.edtCY.getText()));
        this.d.setX(Double.parseDouble(this.edtDX.getText()));
        this.d.setY(Double.parseDouble(this.edtDY.getText()));

    }
    
    public boolean verificaCampoPreenchido(){
    
        return  (!this.edtAX.getText().isEmpty()
                && !this.edtAY.getText().isEmpty()
                && !this.edtBX.getText().isEmpty()
                && !this.edtBY.getText().isEmpty()
                && !this.edtCX.getText().isEmpty()
                && !this.edtCY.getText().isEmpty()
                && !this.edtDX.getText().isEmpty()
                && !this.edtDY.getText().isEmpty());
                
    }
    
    private void voltar(){
        
        this.setVisible(false);
        FrTeste telaPrincipal = new FrTeste();
        telaPrincipal.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArea;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnDiagonal;
    private javax.swing.JButton btnDistancia;
    private javax.swing.JButton btnPerimetro;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JTextField edtAX;
    private javax.swing.JTextField edtAY;
    private javax.swing.JTextField edtBX;
    private javax.swing.JTextField edtBY;
    private javax.swing.JTextField edtCX;
    private javax.swing.JTextField edtCY;
    private javax.swing.JTextField edtDX;
    private javax.swing.JTextField edtDY;
    private javax.swing.JTextArea edtInfo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEntrada;
    private javax.swing.JLabel lblPontoA;
    private javax.swing.JLabel lblPontoA1;
    private javax.swing.JLabel lblPontoA2;
    private javax.swing.JLabel lblPontoD;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables


    private Ponto a = new Ponto();
    private Ponto b = new Ponto();
    private Ponto c = new Ponto();
    private Ponto d = new Ponto();
    private Quadrado q  = new Quadrado();
    
    byte botaoAcionado = 0; //1 - Área, 2 - Existência, 3 - Perímetro e 4 - Diagonal
    
}
