/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author cristiane
 */
public class FrTeste extends javax.swing.JFrame {
    
    FrTriangulo triangulo = new FrTriangulo();
    FrQuadrado quadrado = new FrQuadrado();

    /**
     * Creates new form FrTeste
     */
    public FrTeste() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTriangulo = new javax.swing.JButton();
        btnQuadrado = new javax.swing.JButton();
        lblInput = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnTriangulo.setBackground(new java.awt.Color(204, 204, 255));
        btnTriangulo.setFont(new java.awt.Font("Roboto Condensed", 1, 22)); // NOI18N
        btnTriangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/triangle2.png"))); // NOI18N
        btnTriangulo.setText("TRIÂNGULO");
        btnTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrianguloActionPerformed(evt);
            }
        });

        btnQuadrado.setBackground(new java.awt.Color(204, 204, 255));
        btnQuadrado.setFont(new java.awt.Font("Roboto Condensed", 1, 22)); // NOI18N
        btnQuadrado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/select.png"))); // NOI18N
        btnQuadrado.setText("QUADRADO");
        btnQuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuadradoActionPerformed(evt);
            }
        });

        lblInput.setFont(new java.awt.Font("Roboto Condensed", 0, 19)); // NOI18N
        lblInput.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInput.setText("Escolha uma opção");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(btnTriangulo)
                        .addGap(18, 18, 18)
                        .addComponent(btnQuadrado))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(lblInput, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTriangulo)
                    .addComponent(btnQuadrado))
                .addGap(18, 18, 18)
                .addComponent(lblInput)
                .addGap(0, 123, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrianguloActionPerformed
        triangulo.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_btnTrianguloActionPerformed

    private void btnQuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuadradoActionPerformed
        quadrado.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnQuadradoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuadrado;
    private javax.swing.JButton btnTriangulo;
    private javax.swing.JLabel lblInput;
    // End of variables declaration//GEN-END:variables
}

